name: schooll_website
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  lottie:
  video_player: ^2.1.5
  go_router:
  carousel_indicator:
  flutter_animate: ^4.2.0+1
  url_strategy: ^0.3.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image/
  uses-material-design: true

  fonts:
    - family: Magic Brush
      fonts:
        - asset: assets/fonts/dk-magical-brush/magical_brush.otf
    - family: Dan Sirf
      fonts:
        - asset: assets/fonts/pfdinserif-1/DINPro.otf
    - family: Dan Sirf Bold
      fonts:
        - asset: assets/fonts/pfdinserif-1/DINBold.otf
